#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Generate simple case-folding lookup tables (uppercase, lowercase, titlecase)
# and the "is letter" range table from UnicodeData.txt.
#
# The format is described in:
#   https://www.unicode.org/reports/tr44/#UnicodeData.txt
#
# We use fields:
#   [0]  codepoint               (hex, no prefix)
#   [2]  general category        (Lu/Ll/Lt/Lm/Lo/...)
#   [12] simple uppercase mapping
#   [13] simple lowercase mapping
#   [14] simple titlecase mapping
#
# Only simple (1:1) case mappings are emitted.  Complex mappings such as
# German "sharp s" -> "SS" (which expand to multiple codepoints) live in
# SpecialCasing.txt and are out of scope here.

import sys

def parse_unicode_data(path):
    upper = []         # (cp, upper_cp)
    lower = []         # (cp, lower_cp)
    title = []         # (cp, title_cp) where title != upper
    letter_ranges = [] # list of (start, end) inclusive

    # Large contiguous blocks (CJK ideographs, Hangul syllables, etc.) are
    # encoded as a pair of marker lines: <..., First> at the range start and
    # <..., Last> at the range end.  We expand them into a single range.
    range_start = None
    range_category = None

    for line in open(path):
        fields = line.rstrip("\n").split(";")
        if len(fields) < 15:
            continue

        cp = int(fields[0], 16)
        name = fields[1]
        category = fields[2]
        upper_s = fields[12]
        lower_s = fields[13]
        title_s = fields[14]

        # Handle range markers.  Both First and Last carry the same category;
        # if it's a letter, emit the whole inclusive range.
        if name.endswith(", First>"):
            range_start = cp
            range_category = category
            continue
        if name.endswith(", Last>"):
            if range_start is not None and range_category and range_category.startswith("L"):
                letter_ranges.append((range_start, cp))
            range_start = None
            range_category = None
            continue

        if category.startswith("L"):
            letter_ranges.append((cp, cp))

        if upper_s:
            upper.append((cp, int(upper_s, 16)))
        if lower_s:
            lower.append((cp, int(lower_s, 16)))
        if title_s:
            t = int(title_s, 16)
            # Titlecase usually equals uppercase; only store when it differs
            # so the runtime can fall back to gp_utf_toupper().
            if upper_s and t == int(upper_s, 16):
                pass
            else:
                title.append((cp, t))

    return upper, lower, title, letter_ranges


def collapse_ranges(ranges):
    """Merge a list of (start, end) inclusive ranges into a sorted, coalesced list."""
    if not ranges:
        return []
    ranges = sorted(ranges)
    out = [ranges[0]]
    for start, end in ranges[1:]:
        last_start, last_end = out[-1]
        if start <= last_end + 1:
            out[-1] = (last_start, max(last_end, end))
        else:
            out.append((start, end))
    return out


def emit_map(name, entries):
    entries = sorted(entries)
    print("static const struct gp_utf_case_entry {} [] = {{".format(name))
    for cp, m in entries:
        print("\t{{0x{:04x}, 0x{:04x}}},".format(cp, m))
    print("};")
    print("#define {}_LEN GP_ARRAY_SIZE({})".format(name.upper(), name))
    print()


def emit_ranges(name, ranges):
    print("static const struct gp_utf_range {} [] = {{".format(name))
    for start, end in ranges:
        print("\t{{0x{:04x}, 0x{:04x}}},".format(start, end))
    print("};")
    print("#define {}_LEN GP_ARRAY_SIZE({})".format(name.upper(), name))
    print()


def main():
    if len(sys.argv) != 2:
        print("Usage: gen_utf_case.py UnicodeData.txt", file=sys.stderr)
        sys.exit(1)

    upper, lower, title, letter_ranges = parse_unicode_data(sys.argv[1])

    print("// SPDX-License-Identifier: LGPL-2.1-or-later")
    print("/*")
    print(" * Generated by gen_utf_tables.py")
    print(" *")
    print(" * DO NOT MODIFY THIS FILE DIRECTLY!")
    print(" */")
    print()
    print("#ifndef GP_UTF_CASE_H")
    print("#define GP_UTF_CASE_H")
    print()
    print("#include <stdint.h>")
    print("#include <core/gp_common.h>")
    print()
    print("struct gp_utf_case_entry {")
    print("\tuint32_t cp;")
    print("\tuint32_t mapped;")
    print("};")
    print()
    print("struct gp_utf_range {")
    print("\tuint32_t start;")
    print("\tuint32_t end;")
    print("};")
    print()

    emit_map("gp_utf_upper_map", upper)
    emit_map("gp_utf_lower_map", lower)
    emit_map("gp_utf_title_map", title)
    emit_ranges("gp_utf_letter_ranges", collapse_ranges(letter_ranges))

    print("#endif /* GP_UTF_CASE_H */")


if __name__ == "__main__":
    main()
