TOPDIR=../..

include $(TOPDIR)/pre.mk

CSOURCES=time_stamp.c event_queue.c key_val.c keymap.c

APPS=time_stamp event_queue key_val keymap

include ../tests.mk

include $(TOPDIR)/app.mk
include $(TOPDIR)/post.mk
