TOPDIR=../..

include $(TOPDIR)/pre.mk

CSOURCES=timer.c time_stamp.c event_queue.c key_val.c

APPS=timer time_stamp event_queue key_val keymap

include ../tests.mk

include $(TOPDIR)/app.mk
include $(TOPDIR)/post.mk
