TOPDIR=../..
GENHEADERS=GP_Convert_Scale.gen.h GP_Blit.gen.h GP_Pixel.gen.h \
           GP_GetPutPixel.gen.h GP_Convert.gen.h GP_FnPerBpp.gen.h
LIBNAME=core
include $(TOPDIR)/gen.mk
include $(TOPDIR)/include.mk
