TOPDIR=../..

include $(TOPDIR)/pre.mk

GENHEADERS=GP_Convert_Scale.gen.h GP_Pixel.gen.h \
           GP_GetPutPixel.gen.h GP_Convert.gen.h GP_FnPerBpp.gen.h \
           GP_MixPixels.gen.h GP_GammaCorrection.gen.h GP_GammaPixel.gen.h \
	   GP_WritePixel.gen.h GP_MixPixels2.gen.h

include $(TOPDIR)/gen.mk
include $(TOPDIR)/post.mk
