TOPDIR=../..

include $(TOPDIR)/pre.mk

GENHEADERS=gp_convert_scale.gen.h gp_pixel.gen.h \
           gp_get_put_pixel.gen.h gp_convert.gen.h\
           gp_mix_pixels.gen.h gp_gamma_correction.gen.h gp_gamma_pixel.gen.h \
	   gp_write_pixels.gen.h gp_mix_pixels2.gen.h gp_pixel_pack.gen.h

include $(TOPDIR)/gen.mk
include $(TOPDIR)/post.mk
