TOPDIR=..
include $(TOPDIR)/pre.mk

SUBDIRS=core framework loaders gfx filters input utils

loaders: framework
gfx: framework
core: framework
filters: framework
input: framework
widgets: framework

include $(TOPDIR)/post.mk
