TOPDIR=../..
SUBDIRS=core loaders backends gfx filters text input grabbers
CLEAN+=*.pyc

include $(TOPDIR)/pre.mk

INSTALL_FILES=__init__.py utils.py

include $(TOPDIR)/pyinst.mk
include $(TOPDIR)/post.mk
