/*****************************************************************************
 * This file is part of gfxprim library.                                     *
 *                                                                           *
 * Gfxprim is free software; you can redistribute it and/or                  *
 * modify it under the terms of the GNU Lesser General Public                *
 * License as published by the Free Software Foundation; either              *
 * version 2.1 of the License, or (at your option) any later version.        *
 *                                                                           *
 * Gfxprim is distributed in the hope that it will be useful,                *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Lesser General Public License for more details.                           *
 *                                                                           *
 * You should have received a copy of the GNU Lesser General Public          *
 * License along with gfxprim; if not, write to the Free Software            *
 * Foundation, Inc., 51 Franklin Street, Fifth Floor,                        *
 * Boston, MA  02110-1301  USA                                               *
 *                                                                           *
 * Copyright (C) 2009-2010 Cyril Hrubis <metan@ucw.cz>                       *
 *                                                                           *
 *****************************************************************************/

#include <stdint.h>
#include <inttypes.h>

#include <ctype.h>
#include <errno.h>
#include <string.h>

#include <GP_Debug.h>

#include "GP_PNM.h"

/*

  PNM portable bitmap header
  --------------------------

  Format:
  
  a magick number value of 'P' and one of
   '1' - PBM 2bpp gray ASCII
   '2' - PGM gray      ASCII
   '3' - PPM rgb888    ASCII
   '4' - PBM 2bpp gray BINARY
   '5' - PGM gray      BINARY
   '6' - PPM rgb888    BINARY
  whitespace (blanks, TABs, CRs, LFs).
  ascii width
  whitespace
  ascii height
  whitespace
  maximal value (interval is 0 ... max) (not applicable for PBM)
  width * height ascii or binary values 
  
  lines starting with '#' are comments to the end of line
  
 */

static void try_read_comments(FILE *f)
{
	char c1, c2;

	while (isspace(c1 = fgetc(f)));
	
	ungetc(c1, f);

	while ((c1 = fgetc(f)) == '#') {
		do {
			c2 = fgetc(f);
		} while (c2 != '\n' && c2 != EOF);
	}

	ungetc(c1, f);
}


static char *pnm_names[] = {
	"ASCII encoded PBM",
	"ASCII encoded PGM",
	"ASCII encoded PPM",
	"BINARY encoded PBM",
	"BINARY encoded PGM",
	"BINARY encoded PPM",
};

FILE *GP_ReadPNM(const char *src_path, char *fmt,
                 uint32_t *w, uint32_t *h, uint32_t *depth)
{
	FILE *f = fopen(src_path, "r");
	int ch, err;

	if (f == NULL) {
		GP_DEBUG(1, "Failed to open file '%s': %s",
		         src_path, strerror(errno));
		return NULL;
	}

	ch = fgetc(f);

	if (ch == EOF) {
		err = EIO;
		goto err1;
	}

	if (ch != 'P') {
		GP_DEBUG(1, "Invalid PNM header start '%c' (0x%2x) expecting 'P'",
		         isprint(ch) ? ch : ' ',  ch);
		err = EINVAL;
		goto err1;
	}

	ch = fgetc(f);

	switch (ch) {
	case '4':
	case '1':
		*depth = 1;
	break;
	case '2':
	case '3':
	case '5':
	case '6':
	break;
	default:
		GP_DEBUG(1, "Invalid PNM format 'P%c' (0x%2x)",
		         isprint(ch) ? ch : ' ',  ch);
		err = EINVAL;
		goto err1;
	}
	
	*fmt = ch;

	try_read_comments(f);

	if (fscanf(f, "%"PRIu32"\n", w) < 1) {
		GP_DEBUG(1, "Failed to read PNM header width");
		err = EINVAL;
		goto err1;
	}
	
	try_read_comments(f);
	
	if (fscanf(f, "%"PRIu32"\n", h) < 1) {
		GP_DEBUG(1, "Failed to read PNM header height");
		err = EINVAL;
		goto err1;
	}

	GP_DEBUG(2, "Have %s size %"PRIu32"x%"PRIu32,
	         pnm_names[*fmt - '1'], *w, *h);

	if (*fmt == '1' || *fmt == '3')
		return f;

	try_read_comments(f);
	
	if (fscanf(f, "%"PRIu32"\n", depth) < 1) {
		GP_DEBUG(1, "Failed to read PNM header depth");
		err = EINVAL;
		goto err1;
	}

	return f;
err1:
	fclose(f);
	errno = err;
	return NULL;
}

#define GFXPRIM_SIGNATURE "# Generated by gfxprim http://gfxprim.ucw.cz\n"

FILE *GP_WritePNM(const char *dst_path, char fmt,
                  uint32_t w, uint32_t h, uint32_t depth)
{
	FILE *f = fopen(dst_path, "w");
	int ret;

	ret = fprintf(f, "P%c\n"GFXPRIM_SIGNATURE
	                 "%"PRIu32" %"PRIu32"\n%"PRIu32"\n",
	                 fmt, w, h, depth);

	if (ret < 0) {
		GP_DEBUG(1, "Failed to write PNM header '%s' : %s",
		            dst_path, strerror(errno));
		fclose(f);
		return NULL;
	}

	return f;
}
