/*****************************************************************************
 * This file is part of gfxprim library.                                     *
 *                                                                           *
 * Gfxprim is free software; you can redistribute it and/or                  *
 * modify it under the terms of the GNU Lesser General Public                *
 * License as published by the Free Software Foundation; either              *
 * version 2.1 of the License, or (at your option) any later version.        *
 *                                                                           *
 * Gfxprim is distributed in the hope that it will be useful,                *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Lesser General Public License for more details.                           *
 *                                                                           *
 * You should have received a copy of the GNU Lesser General Public          *
 * License along with gfxprim; if not, write to the Free Software            *
 * Foundation, Inc., 51 Franklin Street, Fifth Floor,                        *
 * Boston, MA  02110-1301  USA                                               *
 *                                                                           *
 * Copyright (C) 2009-2010 Jiri "BlueBear" Dluhos                            *
 *                         <jiri.bluebear.dluhos@gmail.com>                  *
 *                                                                           *
 * Copyright (C) 2009-2011 Cyril Hrubis <metan@ucw.cz>                       *
 *                                                                           *
 *****************************************************************************/

/*

  PGM portable graymap loader/saver.

  Format:
  
  a magick number value of 'P' and '2'
  whitespace (blanks, TABs, CRs, LFs).
  ascii width
  whitespace
  ascii height
  whitespace
  maximal gray value (interval is 0 ... max)
  width * height ascii gray values 
  
  lines starting with '#' are comments to the end of line
  
 */

#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <errno.h>
#include <string.h>
#include <ctype.h>

#include <GP_Debug.h>

#include "GP_PXMCommon.h"
#include "GP_PGM.h"

static void try_read_comments(FILE *f)
{
	char c1, c2;

	while (isspace(c1 = fgetc(f)));
	
	ungetc(c1, f);

	while ((c1 = fgetc(f)) == '#') {
		do {
			c2 = fgetc(f);
		} while (c2 != '\n' && c2 != EOF);
	}

	ungetc(c1, f);
}

GP_RetCode GP_LoadPGM(const char *src_path, GP_Context **res)
{
	FILE *f = fopen(src_path, "r");
	uint32_t w, h, gray;
	GP_PixelType type;
	char h1, h2;

	if (f == NULL) {
		GP_DEBUG(1, "Failed to open file '%s': %s",
		         src_path, strerror(errno));
		return GP_EBADFILE;
	}

	h1 = fgetc(f);
	h2 = fgetc(f);

	if (h1 != 'P' || h2 != '2') {
		GP_DEBUG(1, "Invalid PGM header '%c%c' (0x%2x 0x%2x)",
		         isprint(h1) ? h1 : ' ', isprint(h2) ? h2 : ' ',
			 h1, h2);
		goto err1;
	}

	try_read_comments(f);

	if (fscanf(f, "%"PRIu32, &w) < 1) {
		GP_DEBUG(1, "Failed to read PGM header width");
		goto err1;
	}
	
	try_read_comments(f);
	
	if (fscanf(f, "%"PRIu32, &h) < 1) {
		GP_DEBUG(1, "Failed to read PGM header height");
		goto err1;
	}
	
	try_read_comments(f);
	
	if (fscanf(f, "%"PRIu32, &gray) < 1) {
		GP_DEBUG(1, "Failed to read PGM header gray");
		goto err1;
	}
	
	switch (gray) {
	case 1:
		type = GP_PIXEL_V1;
	break;
	case 3:
		type = GP_PIXEL_V2;
	break;
	case 15:
		type = GP_PIXEL_V4;
	break;
	case 255:
		type = GP_PIXEL_V8;
	break;
	default:
		goto err1;
	}

	*res = GP_ContextAlloc(w, h, type);

	if (res == NULL)
		goto err1;

	switch (gray) {
	case 1:
		if (GP_PXMLoad1bpp(f, *res))
			goto err2;
	break;
	case 3:
		if (GP_PXMLoad2bpp(f, *res))
			goto err2;
	break;
	case 15:
		if (GP_PXMLoad4bpp(f, *res))
			goto err2;
	break;
	case 255:
		if (GP_PXMLoad8bpp(f, *res))
			goto err2;
	break;
	}

	fclose(f);
	return GP_ESUCCESS;
err2:
	free(*res);
err1:
	fclose(f);
	return GP_EBADFILE;
}

GP_RetCode GP_SavePGM(const char *res_path, GP_Context *src)
{
	FILE *f;
	uint32_t gray;

	switch (src->pixel_type) {
	case GP_PIXEL_V1:
		gray = 1;
	break;
	case GP_PIXEL_V2:
		gray = 3;
	break;
	case GP_PIXEL_V4:
		gray = 15;
	break;
	case GP_PIXEL_V8:
		gray = 255;
	break;
	default:
		return GP_ENOIMPL;
	}
	
	f = fopen(res_path, "w");

	if (f == NULL) {
		GP_DEBUG(1, "Failed to open file '%s': %s",
		         res_path, strerror(errno));
		return GP_EBADFILE;
	}

	if (fprintf(f, "P2\n%u %u\n%u\n# Generated by gfxprim\n",
	            (unsigned int) src->w, (unsigned int) src->h, gray) < 3)
		goto err;

	switch (gray) {
	case 1:
		if (GP_PXMSave1bpp(f, src))
			goto err;
	break;
	case 3:
		if (GP_PXMSave2bpp(f, src))
			goto err;
	break;
	//TODO
	case 255:
		if (GP_PXMSave8bpp(f, src))
			goto err;
	break;
	default:
		return GP_ENOIMPL;
	}

	if (fclose(f))
		return GP_EBADFILE;

	return GP_ESUCCESS;
err:
	fclose(f);
	return GP_EBADFILE;
}
