/*****************************************************************************
 * This file is part of gfxprim library.                                     *
 *                                                                           *
 * Gfxprim is free software; you can redistribute it and/or                  *
 * modify it under the terms of the GNU Lesser General Public                *
 * License as published by the Free Software Foundation; either              *
 * version 2.1 of the License, or (at your option) any later version.        *
 *                                                                           *
 * Gfxprim is distributed in the hope that it will be useful,                *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Lesser General Public License for more details.                           *
 *                                                                           *
 * You should have received a copy of the GNU Lesser General Public          *
 * License along with gfxprim; if not, write to the Free Software            *
 * Foundation, Inc., 51 Franklin Street, Fifth Floor,                        *
 * Boston, MA  02110-1301  USA                                               *
 *                                                                           *
 * Copyright (C) 2009-2010 Jiri "BlueBear" Dluhos                            *
 *                         <jiri.bluebear.dluhos@gmail.com>                  *
 *                                                                           *
 * Copyright (C) 2009-2010 Cyril Hrubis <metan@ucw.cz>                       *
 *                                                                           *
 *****************************************************************************/

/*

  PBM portable bitmap loader/saver.

  Format:
  
  a magick number value of 'P' and '1'
  whitespace (blanks, TABs, CRs, LFs).
  ascii width
  whitespace
  ascii height
  whitespace
  width * height symbols '1' or '0' ('1' == black, '0' == white)
  
  lines starting with '#' are comments to the end of line
  
 */

#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>

#include "GP_PXMCommon.h"
#include "GP_PBM.h"

GP_RetCode GP_LoadPBM(const char *src, GP_Context **res)
{
	FILE *f = fopen(src, "r");
	uint32_t w, h;

	if (f == NULL)
		return GP_EBADFILE;

	if (fgetc(f) != 'P' || fgetc(f) != '1')
		goto err1;

	if (fscanf(f, "%"PRIu32"%"PRIu32, &w, &h) < 2)
		goto err1;

	*res = GP_ContextAlloc(w, h, GP_PIXEL_G1);

	if (*res == NULL) {
		fclose(f);
		return GP_ENOMEM;
	}

	if (GP_PXMLoad1bpp(f, *res))
		goto err2;
	
	fclose(f);
	return GP_ESUCCESS;
err2:
	free(*res);
err1:
	fclose(f);
	return GP_EBADFILE;
}

GP_RetCode GP_SavePBM(const char *res, GP_Context *src)
{
	FILE *f;

	if (src->pixel_type != GP_PIXEL_G1)
		return GP_ENOIMPL;
	
	f = fopen(res, "w");

	if (f == NULL)
		return GP_EBADFILE;

	if (fprintf(f, "P1\n%u %u\n# Generated by gfxprim\n",
	            (unsigned int) src->w, (unsigned int) src->h) < 2)
		goto err;

	if (GP_PXMSave1bpp(f, src))
		goto err;

	if (fclose(f))
		return GP_EBADFILE;

	return GP_ESUCCESS;
err:
	fclose(f);
	return GP_EBADFILE;
}
