/*****************************************************************************
 * This file is part of gfxprim library.                                     *
 *                                                                           *
 * Gfxprim is free software; you can redistribute it and/or                  *
 * modify it under the terms of the GNU Lesser General Public                *
 * License as published by the Free Software Foundation; either              *
 * version 2.1 of the License, or (at your option) any later version.        *
 *                                                                           *
 * Gfxprim is distributed in the hope that it will be useful,                *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Lesser General Public License for more details.                           *
 *                                                                           *
 * You should have received a copy of the GNU Lesser General Public          *
 * License along with gfxprim; if not, write to the Free Software            *
 * Foundation, Inc., 51 Franklin Street, Fifth Floor,                        *
 * Boston, MA  02110-1301  USA                                               *
 *                                                                           *
 * Copyright (C) 2009-2010 Jiri "BlueBear" Dluhos                            *
 *                         <jiri.bluebear.dluhos@gmail.com>                  *
 *                                                                           *
 * Copyright (C) 2009-2010 Cyril Hrubis <metan@ucw.cz>                       *
 *                                                                           *
 *****************************************************************************/

#include "GP_PBM.h"

GP_RetCode GP_LoadPBM(const char *src, GP_Context **res)
{
	FILE *f = fopen(src, "r");
	char h1, h2;

	if (f == NULL)
		return GP_EBADFILE;

	if (fscanf(f, "%c%c", &h1, &h2) < 2)
		goto err;

	if (h1 != 'P' || h2 != '1')
		goto err;
	
	return GP_ESUCCESS;
err:
	fclose(f);
	return GP_EBADFILE;
}

#define BITMASK(byte, bit) (((byte)>>bit)&0x01)

static GP_RetCode write_line(FILE *f, const char *data, GP_Context *src)
{
	uint32_t x, max = src->bytes_per_row;
	int ret;

	if (src->w % 8)
		max--;

	for (x = 0; x < max; x++) {
		ret = fprintf(f, "%u %u %u %u %u %u %u %u",
		                 BITMASK(data[x], 0),
		                 BITMASK(data[x], 1),
		                 BITMASK(data[x], 2),
		                 BITMASK(data[x], 3),
		                 BITMASK(data[x], 4),
		                 BITMASK(data[x], 5),
		                 BITMASK(data[x], 6),
		                 BITMASK(data[x], 7));
		if (ret < 0)
			return GP_EBADFILE;
	}

	for (x = 0; x < (src->w % 8); x++) {
		ret = fprintf(f, " %u", BITMASK(data[max], x));

		if (ret < 0)
			return GP_EBADFILE;
	}

	if (fprintf(f, "\n") < 0)
		return GP_EBADFILE;

	return GP_ESUCCESS;
}

GP_RetCode GP_SavePBM(const char *res, GP_Context *src)
{
	FILE *f;
	uint32_t y;
	GP_RetCode ret;

	if (src->pixel_type != GP_PIXEL_G1)
		return GP_ENOIMPL;
	
	f = fopen(res, "w");

	if (f == NULL)
		return GP_EBADFILE;

	if (fprintf(f, "P1\n%u %u\n# Generated by gfxprim\n",
	            (unsigned int) src->w, (unsigned int) src->h) < 2)
		goto err;

	for (y = 0; y < src->h; y++) {
		ret = write_line(f, src->pixels + src->bytes_per_row * y, src);

		if (ret) {
			fclose(f);
			return ret;
		}
	}	

	if (fclose(f))
		return GP_EBADFILE;

	return GP_ESUCCESS;
err:
	fclose(f);
	return GP_EBADFILE;
}
