//SPDX-License-Identifier: LGPL-2.0-or-later

/*

   Copyright (c) 2014-2021 Cyril Hrubis <metan@ucw.cz>

 */

#ifndef GP_WIDGETS_COLOR_SCHEME_H
#define GP_WIDGETS_COLOR_SCHEME_H

#include <widgets/gp_widget_types.h>

/*
 * Decides if the pixmaps generated by application should have dark or light
 * background. There is also default light and dark scheme compiled in the
 * library.
 */
enum gp_widgets_color_scheme {
	GP_WIDGET_COLOR_SCHEME_DEFAULT,
	GP_WIDGET_COLOR_SCHEME_LIGHT,
	GP_WIDGET_COLOR_SCHEME_DARK,
};

/*
 * Toggles current color scheme, reloads colors, redraws application.
 */
void gp_widgets_color_scheme_toggle(void);

/*
 * Sets current color scheme, reloads colors, redraws application.
 */
void gp_widgets_color_scheme_set(enum gp_widgets_color_scheme color_scheme);

/*
 * Returns current color scheme.
 */
enum gp_widgets_color_scheme gp_widgets_color_scheme_get(void);

#endif /* GP_WIDGETS_COLOR_SCHEME_H */
