@ include header.t
/*
 * Inline functions for loading and saving various pixmap formats.
 *
 * Copyright (C) 2017-2026 Cyril Hrubis <metan@ucw.cz>
 */
#include <loaders/gp_loader.h>

/**
 * @brief Autogenerated loader functions.
 * @file gp_loaders.gen.h
 */

@ def reader(fmt):

extern const gp_loader gp_{{fmt}};

/**
 * @brief A function to match a {{fmt}} file signature.
 *
 * @param buf A buffer with at least 32 bytes from the start of the image.
 * @return Returns one on match and zero otherwise.
 */
int gp_match_{{fmt}}(const void *buf);

/**
 * @brief Reads a {{fmt}} image from an I/O.
 *
 * @param io A readable I/O channel.
 * @param img A pointer to store the newly allocated image into.
 * @param storage An optional pointer to a data storage to load the metadata
 *                into. Can be NULL if metadata are not required.
 * @param callback A progress callback. The operation can be aborted by a
 *                 non-zero callback return value.
 * @return Zero on success, non-zero on a failure and errno is set.
 */
int gp_read_{{fmt}}_ex(gp_io *io, gp_pixmap **img, gp_storage *storage,
                   gp_progress_cb *callback);

/**
 * @brief Loads a {{fmt}} image from a file.
 *
 * @param src_path A path to an image file.
 * @param callback A progress callback. The operation can be aborted by a
 *                 non-zero callback return value.
 * @return A newly allocated image loaded from the file or NULL in a case of a
 *         failure. In a case of a failure errno is set.
 */
static inline gp_pixmap *gp_load_{{fmt}}(const char *src_path,
                                     gp_progress_cb *callback)
{
        return gp_loader_load_image(&gp_{{fmt}}, src_path, callback);
}

/**
 * @brief Reads a {{fmt}} image from an I/O.
 *
 * @param io A readable I/O channel.
 * @param callback A progress callback. The operation can be aborted by a
 *                 non-zero callback return value.
 * @return A newly allocated image loaded from the I/O or NULL in a case of a
 *         failure. In a case of a failure errno is set.
 */
static inline gp_pixmap *gp_read_{{fmt}}(gp_io *io, gp_progress_cb *callback)
{
        return gp_loader_read_image(&gp_{{fmt}}, io, callback);
}
@ end

@ for fmt in ['bmp', 'jpg', 'png', 'tiff', 'pbm', 'pgm', 'ppm', 'pnm', 'webp']:
{@ reader(fmt) @}

/**
 * @brief Writes a {{fmt}} image to an I/O.
 *
 * @warning Image loader can save only pixmaps with a compatible pixel types.
 *
 * @param src A pixmap to be saved.
 * @param io A writeable I/O.
 * @param callback A progress callback. The operation can be aborted by a
 *                 non-zero callback return value.
 * @return Zero on success, non-zero otherwise and errno is set. The resulting
 *         errno may also be set to any possible error from open(3), write(3),
 *         seek(3), etc.
 */
int gp_write_{{fmt}}(const gp_pixmap *src, gp_io *io,
                 gp_progress_cb *callback);

/**
 * @brief Writes a {{fmt}} image to a file.
 *
 * @warning Image loader can save only pixmaps with a compatible pixel types.
 *
 * @param src A pixmap to be saved.
 * @param dst_path A path to a file to write the image into.
 * @param callback A progress callback. The operation can be aborted by a
 *                 non-zero callback return value.
 * @return Zero on success, non-zero otherwise and errno is set.
 */
static inline int gp_save_{{fmt}}(const gp_pixmap *src, const char *dst_path,
                              gp_progress_cb *callback)
{
	return gp_loader_save_image(&gp_{{fmt}}, src, dst_path, callback);
}

@ for fmt in ['ico', 'jp2', 'pcx', 'gif', 'psp', 'psd', 'heif']:
{@ reader(fmt) @}
