// SPDX-License-Identifier: LGPL-2.1-or-later
/*
 * Generated file, do not edit!
 */

#ifndef INPUT_KEYS_H__
#define INPUT_KEYS_H__

#include <input/gp_event_keys.h>

struct name_val {
	const char *name;
	int val;
};

static struct name_val keys[] = {
	{.name = "Btn0", .val = GP_BTN_0},
	{.name = "Btn1", .val = GP_BTN_1},
	{.name = "Btn2", .val = GP_BTN_2},
	{.name = "Btn3", .val = GP_BTN_3},
	{.name = "Btn4", .val = GP_BTN_4},
	{.name = "Btn5", .val = GP_BTN_5},
	{.name = "Btn6", .val = GP_BTN_6},
	{.name = "Btn7", .val = GP_BTN_7},
	{.name = "Btn8", .val = GP_BTN_8},
	{.name = "Btn9", .val = GP_BTN_9},
	{.name = "BtnBack", .val = GP_BTN_BACK},
	{.name = "BtnBase", .val = GP_BTN_BASE},
	{.name = "BtnBase2", .val = GP_BTN_BASE2},
	{.name = "BtnBase3", .val = GP_BTN_BASE3},
	{.name = "BtnBase4", .val = GP_BTN_BASE4},
	{.name = "BtnBase5", .val = GP_BTN_BASE5},
	{.name = "BtnBase6", .val = GP_BTN_BASE6},
	{.name = "BtnC", .val = GP_BTN_C},
	{.name = "BtnDead", .val = GP_BTN_DEAD},
	{.name = "BtnEast", .val = GP_BTN_EAST},
	{.name = "BtnExtra", .val = GP_BTN_EXTRA},
	{.name = "BtnForward", .val = GP_BTN_FORWARD},
	{.name = "BtnGearUp", .val = GP_BTN_GEAR_UP},
	{.name = "BtnJoystick", .val = GP_BTN_JOYSTICK},
	{.name = "BtnLeft", .val = GP_BTN_LEFT},
	{.name = "BtnMiddle", .val = GP_BTN_MIDDLE},
	{.name = "BtnMode", .val = GP_BTN_MODE},
	{.name = "BtnNorth", .val = GP_BTN_NORTH},
	{.name = "BtnPinkie", .val = GP_BTN_PINKIE},
	{.name = "BtnRight", .val = GP_BTN_RIGHT},
	{.name = "BtnSelect", .val = GP_BTN_SELECT},
	{.name = "BtnSide", .val = GP_BTN_SIDE},
	{.name = "BtnSouth", .val = GP_BTN_SOUTH},
	{.name = "BtnStart", .val = GP_BTN_START},
	{.name = "BtnStylus", .val = GP_BTN_STYLUS},
	{.name = "BtnStylus2", .val = GP_BTN_STYLUS2},
	{.name = "BtnStylus3", .val = GP_BTN_STYLUS3},
	{.name = "BtnTask", .val = GP_BTN_TASK},
	{.name = "BtnThumb", .val = GP_BTN_THUMB},
	{.name = "BtnThumb2", .val = GP_BTN_THUMB2},
	{.name = "BtnThumbl", .val = GP_BTN_THUMBL},
	{.name = "BtnThumbr", .val = GP_BTN_THUMBR},
	{.name = "BtnTl", .val = GP_BTN_TL},
	{.name = "BtnTl2", .val = GP_BTN_TL2},
	{.name = "BtnToolAirbrush", .val = GP_BTN_TOOL_AIRBRUSH},
	{.name = "BtnToolBrush", .val = GP_BTN_TOOL_BRUSH},
	{.name = "BtnToolDoubleTap", .val = GP_BTN_TOOL_DOUBLE_TAP},
	{.name = "BtnToolFinger", .val = GP_BTN_TOOL_FINGER},
	{.name = "BtnToolLens", .val = GP_BTN_TOOL_LENS},
	{.name = "BtnToolMouse", .val = GP_BTN_TOOL_MOUSE},
	{.name = "BtnToolPen", .val = GP_BTN_TOOL_PEN},
	{.name = "BtnToolPencil", .val = GP_BTN_TOOL_PENCIL},
	{.name = "BtnToolQuadTap", .val = GP_BTN_TOOL_QUAD_TAP},
	{.name = "BtnToolQuintTap", .val = GP_BTN_TOOL_QUINT_TAP},
	{.name = "BtnToolRubber", .val = GP_BTN_TOOL_RUBBER},
	{.name = "BtnToolTripleTap", .val = GP_BTN_TOOL_TRIPLE_TAP},
	{.name = "BtnTop", .val = GP_BTN_TOP},
	{.name = "BtnTop2", .val = GP_BTN_TOP2},
	{.name = "BtnTouch", .val = GP_BTN_TOUCH},
	{.name = "BtnTr", .val = GP_BTN_TR},
	{.name = "BtnTr2", .val = GP_BTN_TR2},
	{.name = "BtnWest", .val = GP_BTN_WEST},
	{.name = "BtnWheel", .val = GP_BTN_WHEEL},
	{.name = "BtnZ", .val = GP_BTN_Z},
	{.name = "Key0", .val = GP_KEY_0},
	{.name = "Key1", .val = GP_KEY_1},
	{.name = "Key102nd", .val = GP_KEY_102ND},
	{.name = "Key10channelsDown", .val = GP_KEY_10CHANNELS_DOWN},
	{.name = "Key10channelsUp", .val = GP_KEY_10CHANNELS_UP},
	{.name = "Key2", .val = GP_KEY_2},
	{.name = "Key3", .val = GP_KEY_3},
	{.name = "Key4", .val = GP_KEY_4},
	{.name = "Key5", .val = GP_KEY_5},
	{.name = "Key6", .val = GP_KEY_6},
	{.name = "Key7", .val = GP_KEY_7},
	{.name = "Key8", .val = GP_KEY_8},
	{.name = "Key9", .val = GP_KEY_9},
	{.name = "KeyA", .val = GP_KEY_A},
	{.name = "KeyAb", .val = GP_KEY_AB},
	{.name = "KeyAddressBook", .val = GP_KEY_ADDRESS_BOOK},
	{.name = "KeyAgain", .val = GP_KEY_AGAIN},
	{.name = "KeyAltErase", .val = GP_KEY_ALT_ERASE},
	{.name = "KeyAngle", .val = GP_KEY_ANGLE},
	{.name = "KeyApostrophe", .val = GP_KEY_APOSTROPHE},
	{.name = "KeyArchive", .val = GP_KEY_ARCHIVE},
	{.name = "KeyAspectRatio", .val = GP_KEY_ASPECT_RATIO},
	{.name = "KeyAudio", .val = GP_KEY_AUDIO},
	{.name = "KeyAux", .val = GP_KEY_AUX},
	{.name = "KeyB", .val = GP_KEY_B},
	{.name = "KeyBack", .val = GP_KEY_BACK},
	{.name = "KeyBackslash", .val = GP_KEY_BACKSLASH},
	{.name = "KeyBackspace", .val = GP_KEY_BACKSPACE},
	{.name = "KeyBassBoost", .val = GP_KEY_BASS_BOOST},
	{.name = "KeyBattery", .val = GP_KEY_BATTERY},
	{.name = "KeyBlue", .val = GP_KEY_BLUE},
	{.name = "KeyBluetooth", .val = GP_KEY_BLUETOOTH},
	{.name = "KeyBookmarks", .val = GP_KEY_BOOKMARKS},
	{.name = "KeyBreak", .val = GP_KEY_BREAK},
	{.name = "KeyBrightnessAuto", .val = GP_KEY_BRIGHTNESS_AUTO},
	{.name = "KeyBrightnessCycle", .val = GP_KEY_BRIGHTNESS_CYCLE},
	{.name = "KeyBrightnessDown", .val = GP_KEY_BRIGHTNESS_DOWN},
	{.name = "KeyBrightnessUp", .val = GP_KEY_BRIGHTNESS_UP},
	{.name = "KeyC", .val = GP_KEY_C},
	{.name = "KeyCalc", .val = GP_KEY_CALC},
	{.name = "KeyCalendar", .val = GP_KEY_CALENDAR},
	{.name = "KeyCamera", .val = GP_KEY_CAMERA},
	{.name = "KeyCancel", .val = GP_KEY_CANCEL},
	{.name = "KeyCapsLock", .val = GP_KEY_CAPS_LOCK},
	{.name = "KeyCd", .val = GP_KEY_CD},
	{.name = "KeyChannel", .val = GP_KEY_CHANNEL},
	{.name = "KeyChannelDown", .val = GP_KEY_CHANNEL_DOWN},
	{.name = "KeyChannelUp", .val = GP_KEY_CHANNEL_UP},
	{.name = "KeyChat", .val = GP_KEY_CHAT},
	{.name = "KeyClear", .val = GP_KEY_CLEAR},
	{.name = "KeyClose", .val = GP_KEY_CLOSE},
	{.name = "KeyCloseCd", .val = GP_KEY_CLOSE_CD},
	{.name = "KeyCoffee", .val = GP_KEY_COFFEE},
	{.name = "KeyComma", .val = GP_KEY_COMMA},
	{.name = "KeyCompose", .val = GP_KEY_COMPOSE},
	{.name = "KeyComputer", .val = GP_KEY_COMPUTER},
	{.name = "KeyConfig", .val = GP_KEY_CONFIG},
	{.name = "KeyConnect", .val = GP_KEY_CONNECT},
	{.name = "KeyContextMenu", .val = GP_KEY_CONTEXT_MENU},
	{.name = "KeyCopy", .val = GP_KEY_COPY},
	{.name = "KeyCut", .val = GP_KEY_CUT},
	{.name = "KeyCycleWindows", .val = GP_KEY_CYCLE_WINDOWS},
	{.name = "KeyD", .val = GP_KEY_D},
	{.name = "KeyDashboard", .val = GP_KEY_DASHBOARD},
	{.name = "KeyDatabase", .val = GP_KEY_DATABASE},
	{.name = "KeyDelete", .val = GP_KEY_DELETE},
	{.name = "KeyDeleteFile", .val = GP_KEY_DELETE_FILE},
	{.name = "KeyDelEol", .val = GP_KEY_DEL_EOL},
	{.name = "KeyDelEos", .val = GP_KEY_DEL_EOS},
	{.name = "KeyDelLine", .val = GP_KEY_DEL_LINE},
	{.name = "KeyDigits", .val = GP_KEY_DIGITS},
	{.name = "KeyDirectory", .val = GP_KEY_DIRECTORY},
	{.name = "KeyDisplayOff", .val = GP_KEY_DISPLAY_OFF},
	{.name = "KeyDisplayToggle", .val = GP_KEY_DISPLAY_TOGGLE},
	{.name = "KeyDocuments", .val = GP_KEY_DOCUMENTS},
	{.name = "KeyDollar", .val = GP_KEY_DOLLAR},
	{.name = "KeyDot", .val = GP_KEY_DOT},
	{.name = "KeyDown", .val = GP_KEY_DOWN},
	{.name = "KeyDvd", .val = GP_KEY_DVD},
	{.name = "KeyE", .val = GP_KEY_E},
	{.name = "KeyEdit", .val = GP_KEY_EDIT},
	{.name = "KeyEditor", .val = GP_KEY_EDITOR},
	{.name = "KeyEjectCd", .val = GP_KEY_EJECT_CD},
	{.name = "KeyEjectCloseCd", .val = GP_KEY_EJECT_CLOSE_CD},
	{.name = "KeyEmail", .val = GP_KEY_EMAIL},
	{.name = "KeyEnd", .val = GP_KEY_END},
	{.name = "KeyEnter", .val = GP_KEY_ENTER},
	{.name = "KeyEpg", .val = GP_KEY_EPG},
	{.name = "KeyEqual", .val = GP_KEY_EQUAL},
	{.name = "KeyEsc", .val = GP_KEY_ESC},
	{.name = "KeyEuro", .val = GP_KEY_EURO},
	{.name = "KeyExit", .val = GP_KEY_EXIT},
	{.name = "KeyF", .val = GP_KEY_F},
	{.name = "KeyF1", .val = GP_KEY_F1},
	{.name = "KeyF10", .val = GP_KEY_F10},
	{.name = "KeyF11", .val = GP_KEY_F11},
	{.name = "KeyF12", .val = GP_KEY_F12},
	{.name = "KeyF13", .val = GP_KEY_F13},
	{.name = "KeyF14", .val = GP_KEY_F14},
	{.name = "KeyF15", .val = GP_KEY_F15},
	{.name = "KeyF16", .val = GP_KEY_F16},
	{.name = "KeyF17", .val = GP_KEY_F17},
	{.name = "KeyF18", .val = GP_KEY_F18},
	{.name = "KeyF19", .val = GP_KEY_F19},
	{.name = "KeyF2", .val = GP_KEY_F2},
	{.name = "KeyF20", .val = GP_KEY_F20},
	{.name = "KeyF21", .val = GP_KEY_F21},
	{.name = "KeyF22", .val = GP_KEY_F22},
	{.name = "KeyF23", .val = GP_KEY_F23},
	{.name = "KeyF24", .val = GP_KEY_F24},
	{.name = "KeyF3", .val = GP_KEY_F3},
	{.name = "KeyF4", .val = GP_KEY_F4},
	{.name = "KeyF5", .val = GP_KEY_F5},
	{.name = "KeyF6", .val = GP_KEY_F6},
	{.name = "KeyF7", .val = GP_KEY_F7},
	{.name = "KeyF8", .val = GP_KEY_F8},
	{.name = "KeyF9", .val = GP_KEY_F9},
	{.name = "KeyFastforward", .val = GP_KEY_FASTFORWARD},
	{.name = "KeyFavorites", .val = GP_KEY_FAVORITES},
	{.name = "KeyFile", .val = GP_KEY_FILE},
	{.name = "KeyFinance", .val = GP_KEY_FINANCE},
	{.name = "KeyFind", .val = GP_KEY_FIND},
	{.name = "KeyFirst", .val = GP_KEY_FIRST},
	{.name = "KeyForward", .val = GP_KEY_FORWARD},
	{.name = "KeyForwardMail", .val = GP_KEY_FORWARD_MAIL},
	{.name = "KeyFrameBack", .val = GP_KEY_FRAME_BACK},
	{.name = "KeyFrameForward", .val = GP_KEY_FRAME_FORWARD},
	{.name = "KeyFront", .val = GP_KEY_FRONT},
	{.name = "KeyFullScreen", .val = GP_KEY_FULL_SCREEN},
	{.name = "KeyG", .val = GP_KEY_G},
	{.name = "KeyGames", .val = GP_KEY_GAMES},
	{.name = "KeyGoto", .val = GP_KEY_GOTO},
	{.name = "KeyGraphicsEditor", .val = GP_KEY_GRAPHICS_EDITOR},
	{.name = "KeyGrave", .val = GP_KEY_GRAVE},
	{.name = "KeyGreen", .val = GP_KEY_GREEN},
	{.name = "KeyH", .val = GP_KEY_H},
	{.name = "KeyHangeul", .val = GP_KEY_HANGEUL},
	{.name = "KeyHangupPhone", .val = GP_KEY_HANGUP_PHONE},
	{.name = "KeyHanja", .val = GP_KEY_HANJA},
	{.name = "KeyHelp", .val = GP_KEY_HELP},
	{.name = "KeyHenkan", .val = GP_KEY_HENKAN},
	{.name = "KeyHiragana", .val = GP_KEY_HIRAGANA},
	{.name = "KeyHome", .val = GP_KEY_HOME},
	{.name = "KeyHomePage", .val = GP_KEY_HOME_PAGE},
	{.name = "KeyHp", .val = GP_KEY_HP},
	{.name = "KeyI", .val = GP_KEY_I},
	{.name = "KeyImages", .val = GP_KEY_IMAGES},
	{.name = "KeyInfo", .val = GP_KEY_INFO},
	{.name = "KeyInsert", .val = GP_KEY_INSERT},
	{.name = "KeyInsLine", .val = GP_KEY_INS_LINE},
	{.name = "KeyIso", .val = GP_KEY_ISO},
	{.name = "KeyJ", .val = GP_KEY_J},
	{.name = "KeyK", .val = GP_KEY_K},
	{.name = "KeyKatakana", .val = GP_KEY_KATAKANA},
	{.name = "KeyKatakanaHiragana", .val = GP_KEY_KATAKANA_HIRAGANA},
	{.name = "KeyKbdIllumDown", .val = GP_KEY_KBD_ILLUM_DOWN},
	{.name = "KeyKbdIllumToggle", .val = GP_KEY_KBD_ILLUM_TOGGLE},
	{.name = "KeyKbdIllumUp", .val = GP_KEY_KBD_ILLUM_UP},
	{.name = "KeyKeyboard", .val = GP_KEY_KEYBOARD},
	{.name = "KeyKp0", .val = GP_KEY_KP_0},
	{.name = "KeyKp1", .val = GP_KEY_KP_1},
	{.name = "KeyKp2", .val = GP_KEY_KP_2},
	{.name = "KeyKp3", .val = GP_KEY_KP_3},
	{.name = "KeyKp4", .val = GP_KEY_KP_4},
	{.name = "KeyKp5", .val = GP_KEY_KP_5},
	{.name = "KeyKp6", .val = GP_KEY_KP_6},
	{.name = "KeyKp7", .val = GP_KEY_KP_7},
	{.name = "KeyKp8", .val = GP_KEY_KP_8},
	{.name = "KeyKp9", .val = GP_KEY_KP_9},
	{.name = "KeyKpAsterisk", .val = GP_KEY_KP_ASTERISK},
	{.name = "KeyKpComma", .val = GP_KEY_KP_COMMA},
	{.name = "KeyKpDot", .val = GP_KEY_KP_DOT},
	{.name = "KeyKpEnter", .val = GP_KEY_KP_ENTER},
	{.name = "KeyKpEqual", .val = GP_KEY_KP_EQUAL},
	{.name = "KeyKpJpcomma", .val = GP_KEY_KP_JPCOMMA},
	{.name = "KeyKpLeftParen", .val = GP_KEY_KP_LEFT_PAREN},
	{.name = "KeyKpMinus", .val = GP_KEY_KP_MINUS},
	{.name = "KeyKpPlus", .val = GP_KEY_KP_PLUS},
	{.name = "KeyKpPlusMinus", .val = GP_KEY_KP_PLUS_MINUS},
	{.name = "KeyKpRightParen", .val = GP_KEY_KP_RIGHT_PAREN},
	{.name = "KeyKpSlash", .val = GP_KEY_KP_SLASH},
	{.name = "KeyL", .val = GP_KEY_L},
	{.name = "KeyLanguage", .val = GP_KEY_LANGUAGE},
	{.name = "KeyLast", .val = GP_KEY_LAST},
	{.name = "KeyLeft", .val = GP_KEY_LEFT},
	{.name = "KeyLeftAlt", .val = GP_KEY_LEFT_ALT},
	{.name = "KeyLeftBrace", .val = GP_KEY_LEFT_BRACE},
	{.name = "KeyLeftCtrl", .val = GP_KEY_LEFT_CTRL},
	{.name = "KeyLeftMeta", .val = GP_KEY_LEFT_META},
	{.name = "KeyLeftShift", .val = GP_KEY_LEFT_SHIFT},
	{.name = "KeyLinefeed", .val = GP_KEY_LINEFEED},
	{.name = "KeyList", .val = GP_KEY_LIST},
	{.name = "KeyLogoff", .val = GP_KEY_LOGOFF},
	{.name = "KeyM", .val = GP_KEY_M},
	{.name = "KeyMacro", .val = GP_KEY_MACRO},
	{.name = "KeyMail", .val = GP_KEY_MAIL},
	{.name = "KeyMedia", .val = GP_KEY_MEDIA},
	{.name = "KeyMediaRepeat", .val = GP_KEY_MEDIA_REPEAT},
	{.name = "KeyMemo", .val = GP_KEY_MEMO},
	{.name = "KeyMenu", .val = GP_KEY_MENU},
	{.name = "KeyMessenger", .val = GP_KEY_MESSENGER},
	{.name = "KeyMhp", .val = GP_KEY_MHP},
	{.name = "KeyMicMute", .val = GP_KEY_MIC_MUTE},
	{.name = "KeyMinus", .val = GP_KEY_MINUS},
	{.name = "KeyMode", .val = GP_KEY_MODE},
	{.name = "KeyMove", .val = GP_KEY_MOVE},
	{.name = "KeyMp3", .val = GP_KEY_MP3},
	{.name = "KeyMsdos", .val = GP_KEY_MSDOS},
	{.name = "KeyMuhenkan", .val = GP_KEY_MUHENKAN},
	{.name = "KeyMute", .val = GP_KEY_MUTE},
	{.name = "KeyN", .val = GP_KEY_N},
	{.name = "KeyNew", .val = GP_KEY_NEW},
	{.name = "KeyNews", .val = GP_KEY_NEWS},
	{.name = "KeyNext", .val = GP_KEY_NEXT},
	{.name = "KeyNextSong", .val = GP_KEY_NEXT_SONG},
	{.name = "KeyNotificationCenter", .val = GP_KEY_NOTIFICATION_CENTER},
	{.name = "KeyNumLock", .val = GP_KEY_NUM_LOCK},
	{.name = "KeyO", .val = GP_KEY_O},
	{.name = "KeyOk", .val = GP_KEY_OK},
	{.name = "KeyOpen", .val = GP_KEY_OPEN},
	{.name = "KeyOption", .val = GP_KEY_OPTION},
	{.name = "KeyP", .val = GP_KEY_P},
	{.name = "KeyPageDown", .val = GP_KEY_PAGE_DOWN},
	{.name = "KeyPageUp", .val = GP_KEY_PAGE_UP},
	{.name = "KeyPaste", .val = GP_KEY_PASTE},
	{.name = "KeyPause", .val = GP_KEY_PAUSE},
	{.name = "KeyPauseCd", .val = GP_KEY_PAUSE_CD},
	{.name = "KeyPc", .val = GP_KEY_PC},
	{.name = "KeyPhone", .val = GP_KEY_PHONE},
	{.name = "KeyPickupPhone", .val = GP_KEY_PICKUP_PHONE},
	{.name = "KeyPlay", .val = GP_KEY_PLAY},
	{.name = "KeyPlayer", .val = GP_KEY_PLAYER},
	{.name = "KeyPlayCd", .val = GP_KEY_PLAY_CD},
	{.name = "KeyPlayPause", .val = GP_KEY_PLAY_PAUSE},
	{.name = "KeyPower", .val = GP_KEY_POWER},
	{.name = "KeyPower2", .val = GP_KEY_POWER2},
	{.name = "KeyPresentation", .val = GP_KEY_PRESENTATION},
	{.name = "KeyPrevious", .val = GP_KEY_PREVIOUS},
	{.name = "KeyPreviousSong", .val = GP_KEY_PREVIOUS_SONG},
	{.name = "KeyPrint", .val = GP_KEY_PRINT},
	{.name = "KeyProg1", .val = GP_KEY_PROG1},
	{.name = "KeyProg2", .val = GP_KEY_PROG2},
	{.name = "KeyProg3", .val = GP_KEY_PROG3},
	{.name = "KeyProg4", .val = GP_KEY_PROG4},
	{.name = "KeyProgram", .val = GP_KEY_PROGRAM},
	{.name = "KeyProps", .val = GP_KEY_PROPS},
	{.name = "KeyPvr", .val = GP_KEY_PVR},
	{.name = "KeyQ", .val = GP_KEY_Q},
	{.name = "KeyQuestion", .val = GP_KEY_QUESTION},
	{.name = "KeyR", .val = GP_KEY_R},
	{.name = "KeyRadio", .val = GP_KEY_RADIO},
	{.name = "KeyRecord", .val = GP_KEY_RECORD},
	{.name = "KeyRed", .val = GP_KEY_RED},
	{.name = "KeyRedo", .val = GP_KEY_REDO},
	{.name = "KeyRefresh", .val = GP_KEY_REFRESH},
	{.name = "KeyReply", .val = GP_KEY_REPLY},
	{.name = "KeyRestart", .val = GP_KEY_RESTART},
	{.name = "KeyRewind", .val = GP_KEY_REWIND},
	{.name = "KeyRfkill", .val = GP_KEY_RFKILL},
	{.name = "KeyRight", .val = GP_KEY_RIGHT},
	{.name = "KeyRightAlt", .val = GP_KEY_RIGHT_ALT},
	{.name = "KeyRightBrace", .val = GP_KEY_RIGHT_BRACE},
	{.name = "KeyRightCtrl", .val = GP_KEY_RIGHT_CTRL},
	{.name = "KeyRightMeta", .val = GP_KEY_RIGHT_META},
	{.name = "KeyRightShift", .val = GP_KEY_RIGHT_SHIFT},
	{.name = "KeyRo", .val = GP_KEY_RO},
	{.name = "KeyRotateDisplay", .val = GP_KEY_ROTATE_DISPLAY},
	{.name = "KeyS", .val = GP_KEY_S},
	{.name = "KeySat", .val = GP_KEY_SAT},
	{.name = "KeySat2", .val = GP_KEY_SAT2},
	{.name = "KeySave", .val = GP_KEY_SAVE},
	{.name = "KeyScale", .val = GP_KEY_SCALE},
	{.name = "KeyScrollDown", .val = GP_KEY_SCROLL_DOWN},
	{.name = "KeyScrollLock", .val = GP_KEY_SCROLL_LOCK},
	{.name = "KeyScrollUp", .val = GP_KEY_SCROLL_UP},
	{.name = "KeySearch", .val = GP_KEY_SEARCH},
	{.name = "KeySelect", .val = GP_KEY_SELECT},
	{.name = "KeySemicolon", .val = GP_KEY_SEMICOLON},
	{.name = "KeySend", .val = GP_KEY_SEND},
	{.name = "KeySendFile", .val = GP_KEY_SEND_FILE},
	{.name = "KeySetup", .val = GP_KEY_SETUP},
	{.name = "KeyShop", .val = GP_KEY_SHOP},
	{.name = "KeyShuffle", .val = GP_KEY_SHUFFLE},
	{.name = "KeySlash", .val = GP_KEY_SLASH},
	{.name = "KeySleep", .val = GP_KEY_SLEEP},
	{.name = "KeySlow", .val = GP_KEY_SLOW},
	{.name = "KeySound", .val = GP_KEY_SOUND},
	{.name = "KeySpace", .val = GP_KEY_SPACE},
	{.name = "KeySpellCheck", .val = GP_KEY_SPELL_CHECK},
	{.name = "KeySport", .val = GP_KEY_SPORT},
	{.name = "KeySpreadsheet", .val = GP_KEY_SPREADSHEET},
	{.name = "KeyStop", .val = GP_KEY_STOP},
	{.name = "KeyStopCd", .val = GP_KEY_STOP_CD},
	{.name = "KeySubtitle", .val = GP_KEY_SUBTITLE},
	{.name = "KeySuspend", .val = GP_KEY_SUSPEND},
	{.name = "KeySwitchVideoMode", .val = GP_KEY_SWITCH_VIDEO_MODE},
	{.name = "KeySysrq", .val = GP_KEY_SYSRQ},
	{.name = "KeyT", .val = GP_KEY_T},
	{.name = "KeyTab", .val = GP_KEY_TAB},
	{.name = "KeyTape", .val = GP_KEY_TAPE},
	{.name = "KeyTeen", .val = GP_KEY_TEEN},
	{.name = "KeyText", .val = GP_KEY_TEXT},
	{.name = "KeyTime", .val = GP_KEY_TIME},
	{.name = "KeyTitle", .val = GP_KEY_TITLE},
	{.name = "KeyTuner", .val = GP_KEY_TUNER},
	{.name = "KeyTv", .val = GP_KEY_TV},
	{.name = "KeyTv2", .val = GP_KEY_TV2},
	{.name = "KeyTwen", .val = GP_KEY_TWEN},
	{.name = "KeyU", .val = GP_KEY_U},
	{.name = "KeyUndo", .val = GP_KEY_UNDO},
	{.name = "KeyUnknown", .val = GP_KEY_UNKNOWN},
	{.name = "KeyUp", .val = GP_KEY_UP},
	{.name = "KeyUwb", .val = GP_KEY_UWB},
	{.name = "KeyV", .val = GP_KEY_V},
	{.name = "KeyVcr", .val = GP_KEY_VCR},
	{.name = "KeyVcr2", .val = GP_KEY_VCR2},
	{.name = "KeyVendor", .val = GP_KEY_VENDOR},
	{.name = "KeyVideo", .val = GP_KEY_VIDEO},
	{.name = "KeyVideoNext", .val = GP_KEY_VIDEO_NEXT},
	{.name = "KeyVideoPhone", .val = GP_KEY_VIDEO_PHONE},
	{.name = "KeyVideoPrev", .val = GP_KEY_VIDEO_PREV},
	{.name = "KeyVoiceMail", .val = GP_KEY_VOICE_MAIL},
	{.name = "KeyVolumeDown", .val = GP_KEY_VOLUME_DOWN},
	{.name = "KeyVolumeUp", .val = GP_KEY_VOLUME_UP},
	{.name = "KeyW", .val = GP_KEY_W},
	{.name = "KeyWakeup", .val = GP_KEY_WAKEUP},
	{.name = "KeyWlan", .val = GP_KEY_WLAN},
	{.name = "KeyWordProcessor", .val = GP_KEY_WORD_PROCESSOR},
	{.name = "KeyWwan", .val = GP_KEY_WWAN},
	{.name = "KeyWww", .val = GP_KEY_WWW},
	{.name = "KeyX", .val = GP_KEY_X},
	{.name = "KeyXfer", .val = GP_KEY_XFER},
	{.name = "KeyY", .val = GP_KEY_Y},
	{.name = "KeyYellow", .val = GP_KEY_YELLOW},
	{.name = "KeyYen", .val = GP_KEY_YEN},
	{.name = "KeyZ", .val = GP_KEY_Z},
	{.name = "KeyZenkakuhankaku", .val = GP_KEY_ZENKAKUHANKAKU},
	{.name = "KeyZoomIn", .val = GP_KEY_ZOOM_IN},
	{.name = "KeyZoomOut", .val = GP_KEY_ZOOM_OUT},
	{.name = "KeyZoomReset", .val = GP_KEY_ZOOM_RESET},
};

static const char *key_names[] = {
	[GP_BTN_0] = "Btn0",
	[GP_BTN_1] = "Btn1",
	[GP_BTN_2] = "Btn2",
	[GP_BTN_3] = "Btn3",
	[GP_BTN_4] = "Btn4",
	[GP_BTN_5] = "Btn5",
	[GP_BTN_6] = "Btn6",
	[GP_BTN_7] = "Btn7",
	[GP_BTN_8] = "Btn8",
	[GP_BTN_9] = "Btn9",
	[GP_BTN_BACK] = "BtnBack",
	[GP_BTN_BASE] = "BtnBase",
	[GP_BTN_BASE2] = "BtnBase2",
	[GP_BTN_BASE3] = "BtnBase3",
	[GP_BTN_BASE4] = "BtnBase4",
	[GP_BTN_BASE5] = "BtnBase5",
	[GP_BTN_BASE6] = "BtnBase6",
	[GP_BTN_C] = "BtnC",
	[GP_BTN_DEAD] = "BtnDead",
	[GP_BTN_EAST] = "BtnEast",
	[GP_BTN_EXTRA] = "BtnExtra",
	[GP_BTN_FORWARD] = "BtnForward",
	[GP_BTN_GEAR_UP] = "BtnGearUp",
	[GP_BTN_JOYSTICK] = "BtnJoystick",
	[GP_BTN_LEFT] = "BtnLeft",
	[GP_BTN_MIDDLE] = "BtnMiddle",
	[GP_BTN_MODE] = "BtnMode",
	[GP_BTN_NORTH] = "BtnNorth",
	[GP_BTN_PINKIE] = "BtnPinkie",
	[GP_BTN_RIGHT] = "BtnRight",
	[GP_BTN_SELECT] = "BtnSelect",
	[GP_BTN_SIDE] = "BtnSide",
	[GP_BTN_SOUTH] = "BtnSouth",
	[GP_BTN_START] = "BtnStart",
	[GP_BTN_STYLUS] = "BtnStylus",
	[GP_BTN_STYLUS2] = "BtnStylus2",
	[GP_BTN_STYLUS3] = "BtnStylus3",
	[GP_BTN_TASK] = "BtnTask",
	[GP_BTN_THUMB] = "BtnThumb",
	[GP_BTN_THUMB2] = "BtnThumb2",
	[GP_BTN_THUMBL] = "BtnThumbl",
	[GP_BTN_THUMBR] = "BtnThumbr",
	[GP_BTN_TL] = "BtnTl",
	[GP_BTN_TL2] = "BtnTl2",
	[GP_BTN_TOOL_AIRBRUSH] = "BtnToolAirbrush",
	[GP_BTN_TOOL_BRUSH] = "BtnToolBrush",
	[GP_BTN_TOOL_DOUBLE_TAP] = "BtnToolDoubleTap",
	[GP_BTN_TOOL_FINGER] = "BtnToolFinger",
	[GP_BTN_TOOL_LENS] = "BtnToolLens",
	[GP_BTN_TOOL_MOUSE] = "BtnToolMouse",
	[GP_BTN_TOOL_PEN] = "BtnToolPen",
	[GP_BTN_TOOL_PENCIL] = "BtnToolPencil",
	[GP_BTN_TOOL_QUAD_TAP] = "BtnToolQuadTap",
	[GP_BTN_TOOL_QUINT_TAP] = "BtnToolQuintTap",
	[GP_BTN_TOOL_RUBBER] = "BtnToolRubber",
	[GP_BTN_TOOL_TRIPLE_TAP] = "BtnToolTripleTap",
	[GP_BTN_TOP] = "BtnTop",
	[GP_BTN_TOP2] = "BtnTop2",
	[GP_BTN_TOUCH] = "BtnTouch",
	[GP_BTN_TR] = "BtnTr",
	[GP_BTN_TR2] = "BtnTr2",
	[GP_BTN_WEST] = "BtnWest",
	[GP_BTN_WHEEL] = "BtnWheel",
	[GP_BTN_Z] = "BtnZ",
	[GP_KEY_0] = "0",
	[GP_KEY_1] = "1",
	[GP_KEY_102ND] = "102nd",
	[GP_KEY_10CHANNELS_DOWN] = "10channelsDown",
	[GP_KEY_10CHANNELS_UP] = "10channelsUp",
	[GP_KEY_2] = "2",
	[GP_KEY_3] = "3",
	[GP_KEY_4] = "4",
	[GP_KEY_5] = "5",
	[GP_KEY_6] = "6",
	[GP_KEY_7] = "7",
	[GP_KEY_8] = "8",
	[GP_KEY_9] = "9",
	[GP_KEY_A] = "A",
	[GP_KEY_AB] = "Ab",
	[GP_KEY_ADDRESS_BOOK] = "AddressBook",
	[GP_KEY_AGAIN] = "Again",
	[GP_KEY_ALT_ERASE] = "AltErase",
	[GP_KEY_ANGLE] = "Angle",
	[GP_KEY_APOSTROPHE] = "Apostrophe",
	[GP_KEY_ARCHIVE] = "Archive",
	[GP_KEY_ASPECT_RATIO] = "AspectRatio",
	[GP_KEY_AUDIO] = "Audio",
	[GP_KEY_AUX] = "Aux",
	[GP_KEY_B] = "B",
	[GP_KEY_BACK] = "Back",
	[GP_KEY_BACKSLASH] = "Backslash",
	[GP_KEY_BACKSPACE] = "Backspace",
	[GP_KEY_BASS_BOOST] = "BassBoost",
	[GP_KEY_BATTERY] = "Battery",
	[GP_KEY_BLUE] = "Blue",
	[GP_KEY_BLUETOOTH] = "Bluetooth",
	[GP_KEY_BOOKMARKS] = "Bookmarks",
	[GP_KEY_BREAK] = "Break",
	[GP_KEY_BRIGHTNESS_AUTO] = "BrightnessAuto",
	[GP_KEY_BRIGHTNESS_CYCLE] = "BrightnessCycle",
	[GP_KEY_BRIGHTNESS_DOWN] = "BrightnessDown",
	[GP_KEY_BRIGHTNESS_UP] = "BrightnessUp",
	[GP_KEY_C] = "C",
	[GP_KEY_CALC] = "Calc",
	[GP_KEY_CALENDAR] = "Calendar",
	[GP_KEY_CAMERA] = "Camera",
	[GP_KEY_CANCEL] = "Cancel",
	[GP_KEY_CAPS_LOCK] = "CapsLock",
	[GP_KEY_CD] = "Cd",
	[GP_KEY_CHANNEL] = "Channel",
	[GP_KEY_CHANNEL_DOWN] = "ChannelDown",
	[GP_KEY_CHANNEL_UP] = "ChannelUp",
	[GP_KEY_CHAT] = "Chat",
	[GP_KEY_CLEAR] = "Clear",
	[GP_KEY_CLOSE] = "Close",
	[GP_KEY_CLOSE_CD] = "CloseCd",
	[GP_KEY_COFFEE] = "Coffee",
	[GP_KEY_COMMA] = "Comma",
	[GP_KEY_COMPOSE] = "Compose",
	[GP_KEY_COMPUTER] = "Computer",
	[GP_KEY_CONFIG] = "Config",
	[GP_KEY_CONNECT] = "Connect",
	[GP_KEY_CONTEXT_MENU] = "ContextMenu",
	[GP_KEY_COPY] = "Copy",
	[GP_KEY_CUT] = "Cut",
	[GP_KEY_CYCLE_WINDOWS] = "CycleWindows",
	[GP_KEY_D] = "D",
	[GP_KEY_DASHBOARD] = "Dashboard",
	[GP_KEY_DATABASE] = "Database",
	[GP_KEY_DELETE] = "Delete",
	[GP_KEY_DELETE_FILE] = "DeleteFile",
	[GP_KEY_DEL_EOL] = "DelEol",
	[GP_KEY_DEL_EOS] = "DelEos",
	[GP_KEY_DEL_LINE] = "DelLine",
	[GP_KEY_DIGITS] = "Digits",
	[GP_KEY_DIRECTORY] = "Directory",
	[GP_KEY_DISPLAY_OFF] = "DisplayOff",
	[GP_KEY_DISPLAY_TOGGLE] = "DisplayToggle",
	[GP_KEY_DOCUMENTS] = "Documents",
	[GP_KEY_DOLLAR] = "Dollar",
	[GP_KEY_DOT] = "Dot",
	[GP_KEY_DOWN] = "Down",
	[GP_KEY_DVD] = "Dvd",
	[GP_KEY_E] = "E",
	[GP_KEY_EDIT] = "Edit",
	[GP_KEY_EDITOR] = "Editor",
	[GP_KEY_EJECT_CD] = "EjectCd",
	[GP_KEY_EJECT_CLOSE_CD] = "EjectCloseCd",
	[GP_KEY_EMAIL] = "Email",
	[GP_KEY_END] = "End",
	[GP_KEY_ENTER] = "Enter",
	[GP_KEY_EPG] = "Epg",
	[GP_KEY_EQUAL] = "Equal",
	[GP_KEY_ESC] = "Esc",
	[GP_KEY_EURO] = "Euro",
	[GP_KEY_EXIT] = "Exit",
	[GP_KEY_F] = "F",
	[GP_KEY_F1] = "F1",
	[GP_KEY_F10] = "F10",
	[GP_KEY_F11] = "F11",
	[GP_KEY_F12] = "F12",
	[GP_KEY_F13] = "F13",
	[GP_KEY_F14] = "F14",
	[GP_KEY_F15] = "F15",
	[GP_KEY_F16] = "F16",
	[GP_KEY_F17] = "F17",
	[GP_KEY_F18] = "F18",
	[GP_KEY_F19] = "F19",
	[GP_KEY_F2] = "F2",
	[GP_KEY_F20] = "F20",
	[GP_KEY_F21] = "F21",
	[GP_KEY_F22] = "F22",
	[GP_KEY_F23] = "F23",
	[GP_KEY_F24] = "F24",
	[GP_KEY_F3] = "F3",
	[GP_KEY_F4] = "F4",
	[GP_KEY_F5] = "F5",
	[GP_KEY_F6] = "F6",
	[GP_KEY_F7] = "F7",
	[GP_KEY_F8] = "F8",
	[GP_KEY_F9] = "F9",
	[GP_KEY_FASTFORWARD] = "Fastforward",
	[GP_KEY_FAVORITES] = "Favorites",
	[GP_KEY_FILE] = "File",
	[GP_KEY_FINANCE] = "Finance",
	[GP_KEY_FIND] = "Find",
	[GP_KEY_FIRST] = "First",
	[GP_KEY_FORWARD] = "Forward",
	[GP_KEY_FORWARD_MAIL] = "ForwardMail",
	[GP_KEY_FRAME_BACK] = "FrameBack",
	[GP_KEY_FRAME_FORWARD] = "FrameForward",
	[GP_KEY_FRONT] = "Front",
	[GP_KEY_FULL_SCREEN] = "FullScreen",
	[GP_KEY_G] = "G",
	[GP_KEY_GAMES] = "Games",
	[GP_KEY_GOTO] = "Goto",
	[GP_KEY_GRAPHICS_EDITOR] = "GraphicsEditor",
	[GP_KEY_GRAVE] = "Grave",
	[GP_KEY_GREEN] = "Green",
	[GP_KEY_H] = "H",
	[GP_KEY_HANGEUL] = "Hangeul",
	[GP_KEY_HANGUP_PHONE] = "HangupPhone",
	[GP_KEY_HANJA] = "Hanja",
	[GP_KEY_HELP] = "Help",
	[GP_KEY_HENKAN] = "Henkan",
	[GP_KEY_HIRAGANA] = "Hiragana",
	[GP_KEY_HOME] = "Home",
	[GP_KEY_HOME_PAGE] = "HomePage",
	[GP_KEY_HP] = "Hp",
	[GP_KEY_I] = "I",
	[GP_KEY_IMAGES] = "Images",
	[GP_KEY_INFO] = "Info",
	[GP_KEY_INSERT] = "Insert",
	[GP_KEY_INS_LINE] = "InsLine",
	[GP_KEY_ISO] = "Iso",
	[GP_KEY_J] = "J",
	[GP_KEY_K] = "K",
	[GP_KEY_KATAKANA] = "Katakana",
	[GP_KEY_KATAKANA_HIRAGANA] = "KatakanaHiragana",
	[GP_KEY_KBD_ILLUM_DOWN] = "KbdIllumDown",
	[GP_KEY_KBD_ILLUM_TOGGLE] = "KbdIllumToggle",
	[GP_KEY_KBD_ILLUM_UP] = "KbdIllumUp",
	[GP_KEY_KEYBOARD] = "Keyboard",
	[GP_KEY_KP_0] = "Kp0",
	[GP_KEY_KP_1] = "Kp1",
	[GP_KEY_KP_2] = "Kp2",
	[GP_KEY_KP_3] = "Kp3",
	[GP_KEY_KP_4] = "Kp4",
	[GP_KEY_KP_5] = "Kp5",
	[GP_KEY_KP_6] = "Kp6",
	[GP_KEY_KP_7] = "Kp7",
	[GP_KEY_KP_8] = "Kp8",
	[GP_KEY_KP_9] = "Kp9",
	[GP_KEY_KP_ASTERISK] = "KpAsterisk",
	[GP_KEY_KP_COMMA] = "KpComma",
	[GP_KEY_KP_DOT] = "KpDot",
	[GP_KEY_KP_ENTER] = "KpEnter",
	[GP_KEY_KP_EQUAL] = "KpEqual",
	[GP_KEY_KP_JPCOMMA] = "KpJpcomma",
	[GP_KEY_KP_LEFT_PAREN] = "KpLeftParen",
	[GP_KEY_KP_MINUS] = "KpMinus",
	[GP_KEY_KP_PLUS] = "KpPlus",
	[GP_KEY_KP_PLUS_MINUS] = "KpPlusMinus",
	[GP_KEY_KP_RIGHT_PAREN] = "KpRightParen",
	[GP_KEY_KP_SLASH] = "KpSlash",
	[GP_KEY_L] = "L",
	[GP_KEY_LANGUAGE] = "Language",
	[GP_KEY_LAST] = "Last",
	[GP_KEY_LEFT] = "Left",
	[GP_KEY_LEFT_ALT] = "LeftAlt",
	[GP_KEY_LEFT_BRACE] = "LeftBrace",
	[GP_KEY_LEFT_CTRL] = "LeftCtrl",
	[GP_KEY_LEFT_META] = "LeftMeta",
	[GP_KEY_LEFT_SHIFT] = "LeftShift",
	[GP_KEY_LINEFEED] = "Linefeed",
	[GP_KEY_LIST] = "List",
	[GP_KEY_LOGOFF] = "Logoff",
	[GP_KEY_M] = "M",
	[GP_KEY_MACRO] = "Macro",
	[GP_KEY_MAIL] = "Mail",
	[GP_KEY_MEDIA] = "Media",
	[GP_KEY_MEDIA_REPEAT] = "MediaRepeat",
	[GP_KEY_MEMO] = "Memo",
	[GP_KEY_MENU] = "Menu",
	[GP_KEY_MESSENGER] = "Messenger",
	[GP_KEY_MHP] = "Mhp",
	[GP_KEY_MIC_MUTE] = "MicMute",
	[GP_KEY_MINUS] = "Minus",
	[GP_KEY_MODE] = "Mode",
	[GP_KEY_MOVE] = "Move",
	[GP_KEY_MP3] = "Mp3",
	[GP_KEY_MSDOS] = "Msdos",
	[GP_KEY_MUHENKAN] = "Muhenkan",
	[GP_KEY_MUTE] = "Mute",
	[GP_KEY_N] = "N",
	[GP_KEY_NEW] = "New",
	[GP_KEY_NEWS] = "News",
	[GP_KEY_NEXT] = "Next",
	[GP_KEY_NEXT_SONG] = "NextSong",
	[GP_KEY_NOTIFICATION_CENTER] = "NotificationCenter",
	[GP_KEY_NUM_LOCK] = "NumLock",
	[GP_KEY_O] = "O",
	[GP_KEY_OK] = "Ok",
	[GP_KEY_OPEN] = "Open",
	[GP_KEY_OPTION] = "Option",
	[GP_KEY_P] = "P",
	[GP_KEY_PAGE_DOWN] = "PageDown",
	[GP_KEY_PAGE_UP] = "PageUp",
	[GP_KEY_PASTE] = "Paste",
	[GP_KEY_PAUSE] = "Pause",
	[GP_KEY_PAUSE_CD] = "PauseCd",
	[GP_KEY_PC] = "Pc",
	[GP_KEY_PHONE] = "Phone",
	[GP_KEY_PICKUP_PHONE] = "PickupPhone",
	[GP_KEY_PLAY] = "Play",
	[GP_KEY_PLAYER] = "Player",
	[GP_KEY_PLAY_CD] = "PlayCd",
	[GP_KEY_PLAY_PAUSE] = "PlayPause",
	[GP_KEY_POWER] = "Power",
	[GP_KEY_POWER2] = "Power2",
	[GP_KEY_PRESENTATION] = "Presentation",
	[GP_KEY_PREVIOUS] = "Previous",
	[GP_KEY_PREVIOUS_SONG] = "PreviousSong",
	[GP_KEY_PRINT] = "Print",
	[GP_KEY_PROG1] = "Prog1",
	[GP_KEY_PROG2] = "Prog2",
	[GP_KEY_PROG3] = "Prog3",
	[GP_KEY_PROG4] = "Prog4",
	[GP_KEY_PROGRAM] = "Program",
	[GP_KEY_PROPS] = "Props",
	[GP_KEY_PVR] = "Pvr",
	[GP_KEY_Q] = "Q",
	[GP_KEY_QUESTION] = "Question",
	[GP_KEY_R] = "R",
	[GP_KEY_RADIO] = "Radio",
	[GP_KEY_RECORD] = "Record",
	[GP_KEY_RED] = "Red",
	[GP_KEY_REDO] = "Redo",
	[GP_KEY_REFRESH] = "Refresh",
	[GP_KEY_REPLY] = "Reply",
	[GP_KEY_RESTART] = "Restart",
	[GP_KEY_REWIND] = "Rewind",
	[GP_KEY_RFKILL] = "Rfkill",
	[GP_KEY_RIGHT] = "Right",
	[GP_KEY_RIGHT_ALT] = "RightAlt",
	[GP_KEY_RIGHT_BRACE] = "RightBrace",
	[GP_KEY_RIGHT_CTRL] = "RightCtrl",
	[GP_KEY_RIGHT_META] = "RightMeta",
	[GP_KEY_RIGHT_SHIFT] = "RightShift",
	[GP_KEY_RO] = "Ro",
	[GP_KEY_ROTATE_DISPLAY] = "RotateDisplay",
	[GP_KEY_S] = "S",
	[GP_KEY_SAT] = "Sat",
	[GP_KEY_SAT2] = "Sat2",
	[GP_KEY_SAVE] = "Save",
	[GP_KEY_SCALE] = "Scale",
	[GP_KEY_SCROLL_DOWN] = "ScrollDown",
	[GP_KEY_SCROLL_LOCK] = "ScrollLock",
	[GP_KEY_SCROLL_UP] = "ScrollUp",
	[GP_KEY_SEARCH] = "Search",
	[GP_KEY_SELECT] = "Select",
	[GP_KEY_SEMICOLON] = "Semicolon",
	[GP_KEY_SEND] = "Send",
	[GP_KEY_SEND_FILE] = "SendFile",
	[GP_KEY_SETUP] = "Setup",
	[GP_KEY_SHOP] = "Shop",
	[GP_KEY_SHUFFLE] = "Shuffle",
	[GP_KEY_SLASH] = "Slash",
	[GP_KEY_SLEEP] = "Sleep",
	[GP_KEY_SLOW] = "Slow",
	[GP_KEY_SOUND] = "Sound",
	[GP_KEY_SPACE] = "Space",
	[GP_KEY_SPELL_CHECK] = "SpellCheck",
	[GP_KEY_SPORT] = "Sport",
	[GP_KEY_SPREADSHEET] = "Spreadsheet",
	[GP_KEY_STOP] = "Stop",
	[GP_KEY_STOP_CD] = "StopCd",
	[GP_KEY_SUBTITLE] = "Subtitle",
	[GP_KEY_SUSPEND] = "Suspend",
	[GP_KEY_SWITCH_VIDEO_MODE] = "SwitchVideoMode",
	[GP_KEY_SYSRQ] = "Sysrq",
	[GP_KEY_T] = "T",
	[GP_KEY_TAB] = "Tab",
	[GP_KEY_TAPE] = "Tape",
	[GP_KEY_TEEN] = "Teen",
	[GP_KEY_TEXT] = "Text",
	[GP_KEY_TIME] = "Time",
	[GP_KEY_TITLE] = "Title",
	[GP_KEY_TUNER] = "Tuner",
	[GP_KEY_TV] = "Tv",
	[GP_KEY_TV2] = "Tv2",
	[GP_KEY_TWEN] = "Twen",
	[GP_KEY_U] = "U",
	[GP_KEY_UNDO] = "Undo",
	[GP_KEY_UNKNOWN] = "Unknown",
	[GP_KEY_UP] = "Up",
	[GP_KEY_UWB] = "Uwb",
	[GP_KEY_V] = "V",
	[GP_KEY_VCR] = "Vcr",
	[GP_KEY_VCR2] = "Vcr2",
	[GP_KEY_VENDOR] = "Vendor",
	[GP_KEY_VIDEO] = "Video",
	[GP_KEY_VIDEO_NEXT] = "VideoNext",
	[GP_KEY_VIDEO_PHONE] = "VideoPhone",
	[GP_KEY_VIDEO_PREV] = "VideoPrev",
	[GP_KEY_VOICE_MAIL] = "VoiceMail",
	[GP_KEY_VOLUME_DOWN] = "VolumeDown",
	[GP_KEY_VOLUME_UP] = "VolumeUp",
	[GP_KEY_W] = "W",
	[GP_KEY_WAKEUP] = "Wakeup",
	[GP_KEY_WLAN] = "Wlan",
	[GP_KEY_WORD_PROCESSOR] = "WordProcessor",
	[GP_KEY_WWAN] = "Wwan",
	[GP_KEY_WWW] = "Www",
	[GP_KEY_X] = "X",
	[GP_KEY_XFER] = "Xfer",
	[GP_KEY_Y] = "Y",
	[GP_KEY_YELLOW] = "Yellow",
	[GP_KEY_YEN] = "Yen",
	[GP_KEY_Z] = "Z",
	[GP_KEY_ZENKAKUHANKAKU] = "Zenkakuhankaku",
	[GP_KEY_ZOOM_IN] = "ZoomIn",
	[GP_KEY_ZOOM_OUT] = "ZoomOut",
	[GP_KEY_ZOOM_RESET] = "ZoomReset",
};

#endif /* INPUT_KEYS_H__ */
