TOPDIR=../..
include $(TOPDIR)/pre.mk

CSOURCES=vec.c matrix.c vec_str.c list.c
APPS=vec matrix vec_str list

include ../tests.mk

include $(TOPDIR)/gen.mk
include $(TOPDIR)/app.mk
include $(TOPDIR)/post.mk
